#ifndef _DEFINE_H__
#define _DEFINE_H__

#define EPS_HMMID 0

#define MAX_TOKEN_NUM 1000
#define MAX_ACTIVE_TOKEN_NUM 500
#define MIN_ACTIVE_TOKEN_NUM 100

#define MAX_TRANSLATION_NUM 50

#define MAX_HYP_NUM MAX_TOKEN_NUM
#define MAX_RESULT_WORD_NUM 500
#define FEATURE_DIM 39
#define FLT_MAX 3.402823466e+38F
#define FLT_MIN -3.0e38F

#define AM_PUNISH_SCORE -10
#define AM_WEIGHT 0.1

#define CUT_OFF_GROUP_NUM 10


#endif

